on:
  push:

jobs:
  build_variables:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Extract Tag Name
        id: build_variables
        run: |
          #... your script remains the same here
          echo "image_tag=$image_tag" >> $GITHUB_ENV
          echo "build_version=$build_version" >> $GITHUB_ENV
          echo "build_full_version=$build_full_version" >> $GITHUB_ENV

    outputs:
      image_tag: ${{ steps.build_variables.outputs.image_tag }}
      build_version: ${{ steps.build_variables.outputs.build_version }}
      build_full_version: ${{ steps.build_variables.outputs.build_full_version }}

  check_variables:
    needs: build_variables
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Check Variables
        run: |
          echo "Image Tag: ${{ needs.build_variables.outputs.image_tag }}"
          echo "Build Version: ${{ needs.build_variables.outputs.build_version }}"
          echo "Build Full Version: ${{ needs.build_variables.outputs.build_full_version }}"
