name: Release to Production

on:
  push:
    tags:
      # Push events matching GA release tags, e.g. v-1.0.0, v-21.1.3, v-4.2.19, etc
      - 'v-[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Not on the main branch. Skipping workflow."
            exit 0
          fi
        shell: bash

      - name: Merge to Production
        run: |
          # Assuming your main branch is 'main' and production branch is 'production'
            echo "Merge to Production"
        env:
          GITHUB_REF: ${{ github.ref }}
