name: Release to Production

on:
  push:
    tags:
      # Push events matching GA release tags, e.g. v-1.0.0, v-21.1.3, v-4.2.19, etc
      - 'v-[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Branch Name
        id: branch
        run: |
          echo  "git ref is : $GITHUB_REF 
          echo "BRANCH_NAME=$(basename $GITHUB_REF)" >> $GITHUB_ENV

      - name: Check Branch
        run: |
          if [[ "${{ steps.branch.outputs.BRANCH_NAME }}" != "main" ]]; then
            echo "Tag was created from a branch other than main."
            exit 1
          else
            echo "Tag was created from the main branch."
          fi
