on:
  push: 
    branches:
      - main

jobs:
  example_matrix:
    strategy:
      matrix:
        project:
          - platform
          - clinical
          - patient
          - revcycle
        environment:
          - staging
        ingress_url: ['ui.staging.psychplus.dev']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.project }}
