name: Deploy Release To Next

on:
  push:
    tags:
      - 'v-[0-9]+.[0-9]+.[0-9]+-next'

jobs:
  build_variables:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      image_tag: ${{ steps.build_variables.outputs.image_tag }}
      build_version: ${{ steps.build_variables.outputs.build_version }}
      build_full_version: ${{ steps.build_variables.outputs.build_full_version }}
    steps:
      - name: Extract Tag Name
        id: build_variables
        run: |
          tag_ref='${{ github.ref }}'
          tag_name=$(echo "$tag_ref" | sed 's|refs/tags/||')
          tag_name="${tag_name:2}"
          echo "Tag Name: $tag_name"
          build_ci_counter="$GITHUB_RUN_NUMBER"
          build_unique_id=$(date +%Y%m%d%H%M%S%N)
          build_version=$tag_name
          build_full_version="$build_version+$build_ci_counter.$build_unique_id"
          next_tag="${tag_name:2:${#tag_name}-5}"
          image_tag="v-$next_tag"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
          echo "build_version=$build_version" >> "$GITHUB_OUTPUT"
          echo "build_full_version=$build_full_version" >> "$GITHUB_OUTPUT"

