name: Release to Production

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  create_draft_release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-1.7.121
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish_draft_release:
    needs: create_draft_release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Publish draft release
        uses: actions/github-script@v5
        with:
          script: |
            const { octokit } = require('@octokit/core');
            const { GitHub, context } = require('@actions/github');
            
            const octokitClient = new GitHub(process.env.GITHUB_TOKEN);
            
            const response = await octokitClient.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.create_release.outputs.create_release.id }},
              draft: false,
            });
            
            console.log('Draft release published:', response.status);
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
