
on:
  push:

jobs:
  build_variables:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      image_tag: ${{ steps.build_variables.outputs.image_tag }}
      build_version: ${{ steps.build_variables.outputs.build_version }}
      build_full_version: ${{ steps.build_variables.outputs.build_full_version }}
    steps:
      - name: Extract Tag Name
        id: build_variables
        run: |
          tag_ref='${{ github.ref }}'
          tag_name="v-1.7.116-rc.7"
          echo "Tag Name: $tag_name"
          build_ci_counter="$GITHUB_RUN_NUMBER"
          build_unique_id=$(date +%Y%m%d%H%M%S%N)
          build_version=$tag_name
          build_full_version="$build_version+$build_ci_counter.$build_unique_id"
          image_tag="v-$build_version"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
          echo "build_version=$build_version" >> "$GITHUB_OUTPUT"
          echo "build_full_version=$build_full_version" >> "$GITHUB_OUTPUT"
  check_variables:
    needs: build_variables
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Check Variables
        run: |
          echo "Image Tag: ${{ needs.build_variables.outputs.image_tag }}"
          echo "Build Version: ${{ needs.build_variables.outputs.build_version }}"
          echo "Build Full Version: ${{ needs.build_variables.outputs.build_full_version }}"
