name: Release to Production

on:
  push:

jobs:
  release:
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  create_draft_release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-1.7.121
          draft: true
          generate_release_notes: true

  publish_draft_release:
    needs: create_draft_release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-1.7.121
          draft: false
          generate_release_notes: true
